import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import AppShell from "./components/AppShell";
import DisableDarkModeOnMobile from "./components/DisableDarkModeOnMobile";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ration Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full" suppressHydrationWarning>
        <AuthProvider>
          <DisableDarkModeOnMobile />
          <Navigation />
          <AppShell>{children}</AppShell>
        </AuthProvider>
      </body>
    </html>
  );
}
